format_version: 10
pipelines:
  no-material-pipeline:
    group: test-group
    materials:
      mygit:
          git: https://github.com/Asmodeus2080/go-cd-material-rep.git
          branch: main
    stages:
      - name: test-stage
        jobs:
          - name: test-job
            tasks:
              - exec:
                  command: echo
                  arguments: ["This is a pipeline with a dummy material."]
