pipelines:
  simple-pipeline:
    group: simple-group
    materials:
      git:
        url: https://github.com/Asmodeus2080/gocd-demo
        branch: main
    stages:
      - name: default-stage
        jobs:
          - name: default-job
            tasks:
              - exec:
                  command: echo
                  arguments: ["Hello, GoCD!"]
