format_version: 10
pipelines:
  basic-pipeline:
    group: test-group
    materials:
      - git:
          url: https://github.com/Asmodeus2080/go-cd-material-rep.git
          branch: main
    template: dummy_template_1