# pipelines:
#   simple-pipeline:
#     group: simple-group
#     # materials:
#     #   git:
#     #     url: https://github.com/Asmodeus2080/go-cd-material-rep.git
#     #     branch: main
#     stages:
#       - name: default-stage
#         jobs:
#           - name: default-job
#             tasks:
#               - exec:
#                   command: echo
#                   arguments: ["Hello, GoCD!"]

pipelines:
  no-material-pipeline:
    group: test-group
    stages:
      - name: test-stage
        jobs:
          - name: test-job
            tasks:
              - exec:
                  command: echo
                  arguments: ["This is a pipeline without a material."]
